server.port : 8080
spring.datasource.url : jdbc:mysql://localhost:3306/store
spring.datasource.driver-class-name : com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.dialect : org.hibernate.dialect.MySQL8Dialect;
spring.jpa.hibernate.ddl-auto : none
spring.jpa.show-sql : false

logging.level.org.hibernate.SQL : debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder : trace

spring.jpa.properties.hibernate.jdbc.batch_size : 0
spring.jpa.properties.hibernate.order_inserts : true
spring.jpa.properties.hibernate.order_updates : true
spring.jpa.properties.hibernate.batch_versioned_data : true

jwt.expired.milliseconds : 1209600000

spring.data.web.pageable.default-page-size : 20

# every night at 3.00
hold.docs.scheduling.cron.expression : 0 0 3 * * ?

mail.debug : false

cors.urls : http://localhost:8082, http://localhost:8081

spring.mail.to.email : daniilshipilov@yandex.ru

report.to.emails : dan.shipilov@gmail.com, elenka050990@gmail.com

spring.mail.host : smtp.mail.ru
spring.mail.from.email : idiplomov@inbox.ru
spring.mail.port : 465
spring.mail.protocol : smtps
spring.mail.properties.mail.smtp.auth : true
spring.mail.debug : false

water.item.number: 161

blocking.users.ids: 1, 77, 79, 80