spring.datasource.url : jdbc:mysql://localhost:3306/sklad
spring.datasource.username : root
spring.datasource.password : testmysql
spring.jpa.hibernate.ddl-auto : none
spring.jpa.show-sql : true
server.port : 8081