spring.datasource.url : jdbc:mysql://localhost:3306/proba
spring.datasource.username : root
spring.datasource.password : testmysql

spring.jpa.hibernate.dialect : org.hibernate.dialect.MySQL8Dialect;
spring.jpa.hibernate.ddl-auto : none
spring.jpa.show-sql : true

logging.level.org.hibernate.SQL : debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder : trace

spring.jpa.properties.hibernate.jdbc.batch_size : 0
spring.jpa.properties.hibernate.order_inserts : true
spring.jpa.properties.hibernate.order_updates : true
spring.jpa.properties.hibernate.batch_versioned_data : true

jwt.secret : password
jwt.expired.milliseconds : 1209600000

spring.data.web.pageable.default-page-size : 20

server.port : 8081

# every night at 3.00
hold.docs.scheduling.cron.expression : 0 0 3 * * ?

our.company.id : 1

cors.urls : http://localhost:8082, http://localhost:8081

spring.mail.to.email : daniilshipilov@yandex.ru

spring.mail.host : smtp.mail.ru
spring.mail.from.email : idiplomov@inbox.ru
spring.mail.password : ${EMAIL_PASSWORD}
spring.mail.port : 465
spring.mail.protocol : smtps
spring.mail.properties.mail.smtp.auth : true
spring.mail.debug : false

item.directories : 1998, 1990