package com.example.store.model.enums;

public enum SettingType {
    PROJECT,
    STORAGE_TO,
    STORAGE_FROM,
    FONT_SIZE,
    INPUT_NULL_VALUE,
    CHECK_HOLDING_ENABLE,
    ADD_REST_FOR_HOLD_1C_DOCS,
    PERIOD_AVERAGE_PRICE,
    DOCS_AVERAGE_PRICE,
    OUR_COMPANY_ID,
    INGREDIENT_DIR_ID,
    HOLDING_DIALOG_ENABLE,
    BLOCK_DOCS_ON_CHECK_HOLDING,
    POSTING_DOC_TYPE_FILTER,
    CHECK_DOC_TYPE_FILTER,
    RECEIPT_DOC_TYPE_FILTER,
    MOVEMENT_DOC_TYPE_FILTER,
    WRITE_OFF_DOC_TYPE_FILTER,
    WITHDRAW_ORDER_DOC_TYPE_FILTER,
    CREDIT_ORDER_DOC_TYPE_FILTER,
    REQUEST_DOC_TYPE_FILTER,
    INVENTORY_DOC_TYPE_FILTER,
    PERIOD_REST_MOVE_DOC_TYPE_FILTER
}
