package com.example.store.model.enums;

public enum SettingType {
    PROJECT,
    STORAGE_TO,
    STORAGE_FROM,
    FONT_SIZE,
    INPUT_NULL_VALUE,
    CHECK_HOLDING_ENABLE,
    ADD_REST_FOR_HOLD_1C_DOCS,
    PERIOD_AVERAGE_PRICE,
    DOCS_AVERAGE_PRICE,
    OUR_COMPANY_ID,
    INGREDIENT_DIR_ID,
    HOLDING_DIALOG_ENABLE
}
